U.buildRoom({
  name: 'hinterlands',
  innerRooms: [ 'record' ],
  build: (foundation, record) => {
    // NOTE: ALL Recs sit together inside of `lands.allRecs`. Need to be
    // careful that Recs generated by Below have custom uids, so that
    // they don't conflict with uids received from Above within allRecs.
    // E.g. imagine Below has a "hut" Rec with uid "00000152" - it's
    // very likely that Above will eventually sync a different Rec with
    // the same uid. That means when Below runs `doUpdate` it will wind
    // up looking for a member Rec with uid "00000152", and it will
    // consider that Rec to be a member of the incoming GroupRec - since
    // it isn't possible for the GroupRec to have a Member with RecType
    // of "hut", an error will be thrown saying something like a Hut
    // Rec was received when a different RecType was expected!
    
    // TODO: Could use a nice big high-level comment explaining why Huts are
    //  Recs, but Lands and Ways are not (although `myLands.arch` is a Rec!)
    
    let doUpdate = (lands, msg) => {
      
      // Updates `lands` based on the contents of `msg`.
      
      let { version, content } = msg;
      if (version !== lands.version + 1) throw new Error(`Tried to move from version ${lands.version} -> ${version}`);
      
      let squad = U.WobSquad();
      let err = U.safe(() => {
        
        // Apply all operations
        let { addRec={}, remRec={}, updRec={} } = content;
        
        // "head" Recs existed before the current update. "tail" Recs are Recs
        // whose existence results from the update. A Rec coming into existence
        // may have member references to both HeadRecs and TailRecs
        let headRecs = lands.allRecs;
        let tailRecs = Map();
        let getHeadOrTailRec = uid => {
          if (headRecs.has(uid)) return headRecs.get(uid);
          if (tailRecs.has(uid)) return tailRecs.get(uid);
          return null;
        };
        
        // Add new Recs with dependency churning
        let waiting = addRec.toArr((v, uid) => v.gain({ uid }));
        while (waiting.length) {
          
          let attempt = waiting;
          waiting = [];
          
          for (let addVals of attempt) {
          
            let { type, value, members, uid } = addVals;
            
            // Convert all members from uid to Rec
            members = members.map(uid => getHeadOrTailRec(uid));
            
            // If a member couldn't be converted wait for a later churn
            if (members.find(m => !m)) { waiting.push(addVals); continue; }
            
            // All members are available - create the Rec!
            let newRec = lands.createRec(type, { uid, value, squad }, ...members);
            tailRecs.set(uid, newRec);
            
          }
          
          if (waiting.length === attempt.length) { // If churn achieved nothing we're stuck
            console.log('Head Recs:', headRecs.toArr((rec, uid) => `${uid}: ${U.nameOf(rec)}`).join('\n'));
            console.log(JSON.stringify(content, null, 2));
            throw new Error(`Unresolvable Rec dependencies`);
          }
          
        }
        
        // Update Recs directly
        updRec.forEach((newValue, uid) => {
          if (!lands.allRecs.has(uid)) throw new Error(`Tried to upd non-existent Rec @ ${uid}`);
          squad.wobble(lands.allRecs.get(uid), newValue);
        });
        
        // Remove Recs directly
        //let shutGroup = Set();
        remRec.forEach((val, uid) => {
          if (!lands.allRecs.has(uid)) throw new Error(`Tried to rem non-existent Rec @ ${uid}`);
          squad.shut(lands.allRecs.get(uid));
        });
        
      });
      
      squad.complete(err);
      
      if (err) { err.message = `Error in "update": ${err.message}`; throw err; }
      
      // We've successfully moved to our next version!
      lands.version = version;
      
    };
    
    let { Rec, Rel } = record;
    let { Hog, WobTmp, HorzScope } = U;
    
    let TERMS = [];
    
    let Lands = U.inspire({ name: 'Lands', methods: () => ({
      init: function({ heartbeatMs=10000, recTypes={}, ...more }) {
        
        if (recTypes.isEmpty()) throw new Error('No "recTypes" provided');
        
        this.heartbeatMs = heartbeatMs;
        this.recTypes = recTypes;
        this.uidCnt = 0;
        this.comWobs = {};
        this.ways = Set();
        
        this.pool = U.setup.CpuPool();
        
        // Keep direct references to all Recs for addressing by uid
        this.allRecs = Map();                       // Map uid -> Rec
        this.hutsBelow = Map();                     // Map cpuId -> Hut
        
        /// {ABOVE=
        
        let { commands=[] } = more;
        this.commands = Set(commands);
        
        // A list of all supported Real Rooms
        this.realRooms = [];
        
        /// =ABOVE} {BELOW=
        
        // Some values to control transmission
        this.version = 0;
        this.heartbeatTimeout = null;
        this.resetHeartbeatTimeout(); // Begin heartbeat
        
        /// =BELOW}
        
        this.arch = this.createRec('arch', { uid: '!arch' }); // rt.arch.create({ uid: '!arch' });
        
        this.addDefaultCommands();
        
      },
      addDefaultCommands: function() {
        
        // Add required commands to Lands
        let requiredCommand = (name, effect) => {
          /// {ABOVE=
          this.commands.add(name);
          /// =ABOVE}
          this.comWob(name).hold(effect);
        };
        requiredCommand('error', async ({ hut, msg, reply }) => { /* nothing */ });
        requiredCommand('fizzle', async ({ hut, msg, reply }) => { /* nothing */ });
        
        /// {ABOVE=
        
        requiredCommand('getInit', async ({ absConn, hut, msg, reply }) => {
          hut.version = 0;                                            // Reset version
          hut.sync = hut.sync.map(v => ({}));                         // Clear current delta
          hut.fols.forEach((fol, rec) => hut.toSync('addRec', rec));  // Gen full sync delta
          
          let update = hut.genSyncTell();
          let initBelow = await foundation.genInitBelow('text/html', absConn, hut.getTerm(), update);
          reply(initBelow);
        });
        requiredCommand('modifyRec', async ({ lands, hut, msg, reply }) => {
          if (!msg.has('uid')) return hut.tell({ command: 'error', type: 'uidMissing', orig: msg });
          if (!msg.has('val')) return hut.tell({ command: 'error', type: 'valMissing', orig: msg });
          let { uid, val } = msg;
          let rec = lands.allRecs.get(uid);
          if (!rec) return hut.tell({ command: 'error', type: 'uidNotFound', orig: msg });
          try { hut.modifyRec(rec, val); }
          catch(err) { hut.tell({ command: 'error', type: 'invalid', message: err.message, orig: msg }); }
        });
        requiredCommand('getFile', async ({ hut, msg, reply }) => {
          reply(U.safe(
            () => foundation.getMountFile(msg.path),
            () => ({ command: 'error', type: 'fileNotFound', orig: msg })
          ));
        });
        requiredCommand('thunThunk', async ({ hut, msg, reply }) => { /* nothing */ });
        
        /// =ABOVE} {BELOW=
        
        requiredCommand('update', ({ lands, hut, msg, reply }) => {
          
          doUpdate(lands, msg);
          
        });
        
        /// =BELOW}
        
      },
      addWay: function(way) { way.lands = this; this.ways.add(way); },
      addReality: function(rootReal, reality) {
        
        // Note: Above, multiple Realities can exist for the same Real.
        // This is because Above includes all *possibile* Reals. The
        // Below, on the other hand, has a single determined Real - so
        // only 1 Reality can exist per Real Below. (VERY theoretically,
        // there could be separate Reals each with their own Reality,
        // Below. Like... something that runs in both Electron and the
        // browser at the same time??)
        
        if (rootReal) {
          if (rootReal.reality) throw new Error(`Real ${rootReal.nameChain.join('.')} already has Reality`);
          rootReal.reality = reality;
        }
        
        /// {ABOVE=
        
        // TODO: Should files be added to the entire foundation? Or only to a particular app?
        // Consider adding the file to the foundation, but also requiring something like:
        // `lands.addServableFile(`${reality.name}.css`);`
        let cssControls = reality.getCssControls();
        foundation.addMountDataAsFile(`${reality.name}.css`, 'text/css', cssControls.cmp);
        return Hog(() => {
          foundation.remMountFile(`${reality.name}.css`);
          if (rootReal) rootReal.reality = null;
        });
        
        /// =ABOVE} {BELOW=
        
        let { query } = foundation.parseUrl(window.location.toString());
        
        let styleElem = document.createElement('link');
        styleElem.setAttribute('rel', 'stylesheet');
        styleElem.setAttribute('type', 'text/css');
        styleElem.setAttribute('media', 'screen');
        styleElem.setAttribute('href', `/!FILE/${reality.name}.css${query.has('spoof') ? `?spoof=${query.spoof}` : ''}`);
        document.head.appendChild(styleElem);
        
        real.dom.id = `${reality.name}`;
        return Hog(() => {
          real.dom.id = '';
          if (rootReal) rootReal.reality = null;
        });
        
        /// =BELOW}
        
      },
      nextUid: function() { return (this.uidCnt++).toString(36).padHead(8, '0'); },
      genUniqueTerm: function() {
        // If we used `getTerm` we could get an infinite loop! Simply exclude
        // any Huts that don't yet have a term
        let terms = Set(this.getAllHuts().map(h => h.term || C.skip));
        
        for (let i = 0; i < 100; i++) { // TODO: This is no good - `100` is arbitrary!
          let ret = TERMS[Math.floor(Math.random() * TERMS.length)]; // TODO: Should use chance room
          if (!terms.has(ret)) return ret;
        }
        throw new Error('Too many huts! Not enough terms!! AHHHH!!!');
      },
      
      createRec: function(name, params={}, ...args) {
        if (!this.recTypes.has(name)) throw new Error(`Invalid RecType name: "${name}"`)
        if (!params.has('uid')) params.uid = this.nextUid();
        params.lands = this;
        let rec = this.recTypes[name].create(params, ...args);
        this.allRecs.set(rec.uid, rec);
        rec.shutWob().hold(() => this.allRecs.rem(rec.uid));
        return rec;
      },
      comWob: function(command) {
        if (!this.comWobs.has(command)) {
          /// {ABOVE=
          if (!this.commands.has(command)) throw new Error(`Invalid command: "${command}"`);
          /// =ABOVE}
          this.comWobs[command] = U.Wob({});
        }
        return this.comWobs[command];
      },
      hear: async function(absConn, hut, msg, reply=null) {
        
        if (msg === null) return;
        
        let { command } = msg;
        
        /// {ABOVE=
        if (!this.commands.has(command)) {
          return hut.tell({ command: 'error', type: 'notRecognized', orig: msg });
        }
        /// =ABOVE}
        
        this.comWob(command).wobble({ lands: this, absConn, hut, msg, reply });
        hut.comWob(command).wobble({ lands: this, absConn, hut, msg, reply });
        
      },
      tell: async function(msg) {
        /// {BELOW=
        this.resetHeartbeatTimeout(); // Already sending a sign of life; defer next heartbeat
        /// =BELOW}
        this.getAllHuts().forEach(hut => hut.tell(msg));
      },
      
      /// {ABOVE=
      setRealRooms: function(realRooms) { this.realRooms = realRooms; },
      /// =ABOVE}
      
      getRootReal: async function(realRoom=foundation.getDefaultRealRoom()) {
        let rootReal = await foundation.getRootReal();
        if (rootReal.reality) throw new Error('Reality already applied');
        let reality = realRoom.Reality('root');
        reality.addFlatLayouts(this.realLayout);
        rootReal.reality = reality;
        rootReal.layout = reality.rootLayout;
        return rootReal;
      },
      
      /// {BELOW=
      resetHeartbeatTimeout: function() {
        if (!this.heartbeatMs) return;
        
        // After exactly `this.heartbeatMs` millis Above will shut us down
        // Therefore we need to be quicker - wait less millis than `this.heartbeatMs`
        clearTimeout(this.heartbeatTimeout);
        this.heartbeatTimeout = setTimeout(() => this.tell({ command: 'thunThunk' }), Math.max(this.heartbeatMs * 0.85, this.heartbeatMs - 2000));
      },
      modifyRec: function(rec, newVal) {
        
        // Called from Below; affects `rec` Above!
        
        // TODO: Validation in {ABOVE= Lands.prototype.modifyRec =ABOVE}
        // and {BELOW= Hut.prototype.modifyRec =BELOW} disagree with
        // each other!
        // TODO: We can prevent the message from happening if `newVal`
        // is a redundant update!
        // TODO: The naming "newVal" (and the "val" property of the
        // "modifyRec" command) don't reflect that "newVal" is often a
        // delta - containing only the changed properties.
        
        let curVal = rec.value;
        if (curVal === newVal) return;
        
        let regUpd = curVal !== null && newVal !== null; // "regular update"; neither value is null
        
        if (regUpd && U.inspOf(curVal) !== U.inspOf(newVal))
          throw new Error(`Tried to update ${U.nameOf(curVal)} -> ${U.nameOf(newVal)}`);
        
        if (regUpd && U.isType(newVal, Object)) {
          let changedProp = false;
          for (let k in newVal) {
            if (!curVal.has(k)) throw new Error(`Tried to add non-existent property: "${k}"`);
            if (curVal[k] !== newVal[k]) changedProp = true;
          }
          if (!changedProp) return; // Tolerate this! No property changed. TODO: Should check recursively if an inner property was also an Object
        }
        
        this.tell({ command: 'modifyRec', uid: rec.uid, val: newVal });
      },
      /// =BELOW}
      
      getAllHuts: function() {
        return this.arch.relWob(rt.archHut, 0).toArr(archHut => archHut.members[1]);
      },
      
      // TODO: async functions shouldn't be named "open" and "shut"
      open: async function() {
        /// {ABOVE=
        TERMS = JSON.parse(await foundation.readFile('room/hinterlands/TERMS.json'));
        /// =ABOVE} {BELOW=
        TERMS = [ 'remote' ]; // Below has only 1 Hut, so only 1 name needed
        /// =BELOW}
        
        /// {ABOVE=
        
        // Temporarily create each supported Reality, and include its
        // compile-time assets
        for (let realRoom of this.realRooms) {
          
          let reality = realRoom.Reality('root'); // This instance exists temporarily
          reality.addFlatLayouts(this.realLayout);
          
          let staticAssets = reality.getCmpTimeFwkAssets();
          staticAssets.forEach(({ contentType, content }, key) => {
            foundation.addMountDataAsFile(key, contentType, content);
          });
          
        }
        
        /// =ABOVE}
        
        await Promise.allArr([ ...this.ways ].map(w => w.open())); // Open all Ways
        
        /// {BELOW=
        let hut = this.getAllHuts().find(() => true)[0];
        await this.hear(null, hut, U.initData); // Lands Below immediately hear the Above's initial update
        /// =BELOW}
      },
      shut: async function() { return Promise.allArr([ ...this.ways ].map(w => w.shut())); }
    })});
    let Hut = U.inspire({ name: 'Hut', insps: { Rec }, methods: (insp, Insp) => ({
      
      init: function({ lands, cpuId, ...supArgs }) {
        
        if (!lands) throw new Error('Missing "lands"');
        if (!cpuId) throw new Error('Missing "cpuId"');
        
        insp.Rec.init.call(this, supArgs);
        this.lands = lands;
        this.cpuId = cpuId;
        this.term = null;
        this.comWobs = {};
        this.ways = Set();
        
        /// {ABOVE=
        // Keep track of which Records the Below for this Hut has followed
        this.version = 0;
        this.fols = Map();
        this.sync = [ 'addRec', 'updRec', 'remRec' ].toObj(v => [ v, {} ]);
        
        // Keep track of whether the Below for this Hut is still communicating
        this.expiryTimeout = null;
        this.syncThrottlePrm = null; // Resolves when we've sent sync to Below
        this.refreshExpiry();
        /// =ABOVE}
        
        /// {TEST=
        this.forceSyncVal = null;
        /// =TEST}
        
      },
      getTerm: function() {
        if (!this.term) this.term = this.lands.genUniqueTerm();
        return this.term;
      },
      comWob: function(command) {
        if (!this.comWobs.has(command)) {
          /// {ABOVE=
          if (!this.lands.commands.has(command)) throw new Error(`Invalid command: "${command}"`);
          /// =ABOVE}
          this.comWobs[command] = U.Wob({});
        }
        return this.comWobs[command];
      },
      
      /// {ABOVE=
      refreshExpiry: function() {
        clearTimeout(this.expiryTimeout);
        this.expiryTimeout = setTimeout(() => this.shut(), this.lands.heartbeatMs);
      },
      
      toSync: function(type, rec) {
        
        if (!this.sync.has(type)) throw new Error(`Invalid type: ${type}`);
        let { addRec, updRec, remRec } = this.sync;
        
        // Can addRec and remRec occur together? NO  (conflicting messages!)
        // Can addRec and updRec occur together? NO  (redundant!)
        // Can remRec and updRec occur together? YES (e.g. animation upon deletion)
        
        if (type === 'addRec') {
          
          if (remRec.has(rec.uid))  delete remRec[rec.uid];
          else                      { delete updRec[rec.uid]; addRec[rec.uid] = rec; }
          
        } else if (type === 'remRec') {
          
          if (addRec.has(rec.uid))  delete addRec[rec.uid];
          else                      remRec[rec.uid] = rec;
          
        } else if (type === 'updRec') {
          
          if (addRec.has(rec.uid))  return; // No "updRec" necessary: already adding!
          else                      updRec[rec.uid] = rec;
          
        }
        
        this.requestSyncBelow();
        
      },
      requestSyncBelow: function() {
        
        // Schedules Below to be synced if not already scheduled
        
        let err = new Error('');
        
        this.syncThrottlePrm = (async () => {
          
          try {
            
            // await this.genSyncThrottlePrm();
            await new Promise(r => foundation.queueTask(r)); // TODO: This could be swapped out (to a timeout, or whatever!)
            
            
            this.syncThrottlePrm = null;
            
            // Hut may have been shut between scheduling and executing sync
            if (this.isShut()) return;
            
            let updateTell = this.genSyncTell();
            if (updateTell) this.tell(updateTell);
            
          } catch(err0) {
            throw err0;
            //err.message = `Error doing sync: ${err0.message}`;
            //throw err;
          }
          
        })();
        
      },
      genSyncTell: function() {
        
        // Generates sync data to bring the Below up to date. Has the side-effect
        // of clearing this Hut's memory of the current delta.
        
        let addRec = this.sync.addRec.map(r => ({ type: r.type.name, value: r.value, members: r.members.map(m => m.uid) }));
        let updRec = this.sync.updRec.map(r => r.value);
        let remRec = this.sync.remRec.map(r => 1);
        
        let content = {};
        if (!addRec.isEmpty()) content.addRec = addRec;
        if (!updRec.isEmpty()) content.updRec = updRec;
        if (!remRec.isEmpty()) content.remRec = remRec;
        
        /// {TEST=
        if (content.isEmpty() && this.forceSyncVal) { content.force = this.forceSyncVal; }
        this.forceSyncVal = null;
        /// =TEST}
        
        if (content.isEmpty()) return null;
        
        this.sync = this.sync.map(v => ({}));
        this.version++;
        return { command: 'update', version: this.version, content };
        
      },
      
      getRecFollowStrength: function(rec) { return (this.fols.get(rec) || { strength: 0 }).strength; },
      setRecFollowStrength: function(rec, strength) {
        
        if (strength < 0) throw new Error(`Invalid strength ${strength} for ${rec.type.name}`);
        
        let fol = this.fols.get(rec) || null;     // The current Follow
        let strength0 = fol ? fol.strength : 0;   // The current FollowStrength
        if (strength === strength0) throw new Error(`Strength is already ${strength}`);
        
        // Our FollowStrength of `rec` is changing! There are 3 possibilities:
        // 1 - Strength moving from =0 to >0 : ADD REC!
        // 2 - Strength moving from >0 to >0 : DO NOTHING!
        // 3 - Strength moving from >0 to =0 : REM REC!
        
        if (!strength0) {                   // ADD
          
          // This HorzScope depends on `rec`. That means if `rec` shuts for
          // any reason, we will stop following it! We can also explicitly
          // cease following `rec` by calling `ap.shut()`
          HorzScope(U.WobVal(rec), (dep, rec, ap) => {
            
            // Track the follow. Note that this is NOT cleaned up with
            // `dep` - e.g. if `rec` shuts, this entry in `this.fols`
            // still persists. Instead use `setRecFollowStrength` to
            // decrement follow strength to 0!
            fol = { strength, ap, modifyAny: Map(), modifyAll: Map() }; // A single "any" and every "all" must pass
            this.fols.set(rec, fol);
            
            // Send a sync
            this.toSync('addRec', rec);
            dep(Hog(() => this.toSync('remRec', rec)));
            
            // Send upd syncs when `rec` wobbles (note `false` indicates non-hastiness)
            dep(rec.hold(val => this.toSync('updRec', rec), false));
            
          });
          return fol;
          
        } else if (strength0 && strength) { // UPD
          
          fol.strength = strength;
          
        } else {                            // REM
          
          // Close the HorzScope
          fol.ap.shut();
          this.fols.delete(rec);
          fol = null;
          
        }
        
        return fol;
        
      },
      followRec: function(rec, modify={}) {
        // TODO: Automatically follow `rec.members`?
        let fol = this.setRecFollowStrength(rec, this.getRecFollowStrength(rec) + 1);
        
        // Note that `fol.modifyAny` and `fol.modifyAll` map functions
        // to the hold strength of that specific function
        let { modifyAny: anyF, modifyAll: allF } = modify;
        if (anyF && !U.isType(anyF, Function)) throw new Error('Invalid "modifyAny" value');
        if (allF && !U.isType(allF, Function)) throw new Error('Invalid "modifyAll" value');
        if (anyF) fol.modifyAny.set(anyF, (fol.modifyAny.get(anyF) || 0) + 1);
        if (allF) fol.modifyAll.set(allF, (fol.modifyAll.get(allF) || 0) + 1);
        
        return Hog(() => {
          let fol = this.setRecFollowStrength(rec, this.getRecFollowStrength(rec) - 1);
          if (fol) {
            if (anyF) { let v = fol.modifyAny.get(anyF); fol.modifyAny[(v > 1) ? 'set' : 'rem'](anyF, v - 1); }
            if (allF) { let v = fol.modifyAll.get(allF); fol.modifyAll[(v > 1) ? 'set' : 'rem'](allF, v - 1); }
          }
        });
      },
      modifyRec: function(rec, newVal) {
        
        // A command from Below has wound us up here. Make sure that the
        // Below has permission to modify this `rec` in the way desired,
        // and if so do the modification.
        
        if (rec.value !== null && newVal.value !== null)
          if (U.inspOf(rec.value) !== U.inspOf(newVal))
            throw new Error(`Can't modify - tried to modify ${U.nameOf(rec.value)} -> ${U.nameOf(newVal)}`);
        
        let fol = this.fols.get(rec);
        if (!fol) throw new Error(`Can't modify `);
        
        // Allow if any "modifyAny" passes and no "modifyAll" fails
        let anyPass = false;
        for (let f of fol.modifyAny.keys()) if (f(newVal)) { anyPass = true; break; }
        if (!anyPass) throw new Error(`Can't modify since no "any" passed`);
        
        let allPass = true;
        for (let f of fol.modifyAll.keys()) if (f(newVal)) { allPass = false; break; }
        if (!allPass) throw new Error(`Can't modify since an "all" denied`);
        
        if (U.isType(newVal, Object)) rec.wobble({ ...(rec.value || {}), ...newVal });
        else                          rec.wobble(newVal);
      },
      
      shut0: function() {
        insp.Rec.shut0.call(this);
        clearTimeout(this.expiryTimeout); this.expiryTimeout = null;
      },
      /// =ABOVE}
      
      /// {TEST=
      // TODO: Only works with TEST && ABOVE...
      forceSync: function(val) { this.forceSyncVal = val; this.requestSyncBelow(); },
      /// =TEST}
      
      tell: function(msg) {
        // TODO: Below picks the lowest cost Way, but Above picks the
        // lowest cost Way **WHICH IS SUPPORTED BY `this` HUT!**
        let bestWay = null;
        for (let way of this.ways) {
          if (!bestWay || (way.server && (way.server.cost < bestWay.server.cost))) bestWay = way;
        }
        
        if (!bestWay) throw new Error(`Hut ${this.address} has no Ways`);
        bestWay.tellHut(this, msg);
      }
    })});
    let Way = U.inspire({ name: 'Way', methods: (insp, Insp) => ({
      init: function({ makeServer }) {
        if (!makeServer) throw new Error('Missing "makeServer"');
        
        this.lands = null;
        this.makeServer = makeServer;
        this.server = null;
        this.serverFunc = null
      },
      
      open: async function() {
        this.server = await this.makeServer();
        this.serverFunc = this.server.hold(absConn => {
          
          // Note there are different strata of "connections":
          // 1) FundamentalConnection (HTTP protocol, SOKT protocol, etc.)
          // 2) AbstractConnection (here, `absConn`):
          //    - Provides connection events; provides state for stateless
          //      FundamentalConnections. Common interface across different
          //      FundamentalConnections
          //    - Patches a number of Fundamental connections together
          // 3) Connected Hut (the thing generated by this function):
          //    - A Rec which lives for the duration of its
          //      AbstractConnection 
          
          // Get the cpuId; ensure it isn't already connected
          let { cpuId } = absConn;
          let isNewCpu = !this.lands.hutsBelow.has(cpuId); // TODO: Is this tracking anything different from `this.lands.pool.cpus`?
          
          let hut = null;
          if (isNewCpu) {
            hut = this.lands.createRec('hut', { cpuId, uid: `!cpuId:${cpuId}` });
            this.lands.hutsBelow.set(cpuId, hut); // Register Hut on Lands
            hut.shutWob().hold(group => this.lands.hutsBelow.rem(cpuId));
          } else {
            hut = this.lands.hutsBelow.get(cpuId);
          }
          
          let holdRelay = absConn.hear.hold(([ msg, reply=null ]) => {
            /// {ABOVE=
            hut.refreshExpiry();
            /// =ABOVE}
            this.lands.hear(absConn, hut, msg, reply);
          });
          hut.ways.add(this);
          
          // Shutting the Connection does most of the cleanup
          absConn.shutWob().hold(group => {
            hut.ways.rem(this);
            if (!holdRelay.isShut()) holdRelay.shut(group);
            if (!hut.isShut() && hut.ways.isEmpty()) hut.shut(group);
          });
          
          // Shutting the Hut shuts the Connection
          hut.shutWob().hold(group => !absConn.isShut() && absConn.shut(group));
          
          // TODO: Can Ways shut? Like if the server loses its ability to perform
          // SOKT connections? Let's assume "no" for now...
          
          // Hut and Way stay connected while Connection lives. If all
          // Connections close, the Hut is shut.
          
          // Attach the Hut to the Way and to the Lands
          // TODO: Right now the lands tracks the Hut both through `hutsBelow` and
          // through `archHut`... ideally only one should be used! I think we can't
          // create the ArchHut too early in this function, or else initial holders
          // will receive a Hut that is lacking some functionality
          if (isNewCpu) this.lands.createRec('archHut', { uid: `!hutTerm:${hut.getTerm()}` }, this.lands.arch, hut);
          
        });
      },
      shut: async function() { this.serverFunc.shut(); },
      
      tellHut: function(hut, msg) {
        let conn = this.lands.pool.getCpuConn(hut.cpuId, this.server);
        if (!conn) throw new Error(`Tried to tell disconnected hut: ${hut.getTerm()}`);
        conn.tell(msg);
      }
    })});
    
    let { rt, add } = record.recTyper();
    add('arch',     Rec);
    add('hut',      Hut);
    add('archHut',  Rec, '1M', rt.arch, rt.hut);
    
    let content = { Lands, Hut, Way, rt };
    
    /// {TEST=
    
    let parseInitData = msg => {
      let endBit = msg.substr(msg.indexOf('// ==== File:' + ' hut.js'));
      let initDataMatch = endBit.match(/U\.initData = (.*);\s*U\.debugLineData = /);
      if (!initDataMatch) throw new Error(`Couldn't parse invalid initData`);
      return JSON.parse(initDataMatch[1]);
    };
    
    content.test = rootKeep => rootKeep.contain(k => {
      
      let testData = null;
      k.sandwich.before = async () => {
        
        let cpuIdCnt = 0;
        
        let { rt: trt, add } = record.recTyper();
        add('loc',        Rec);
        add('item',       Rec);
        add('man',        Rec);
        add('hat',        Rec);
        add('store',      Rec);
        add('manHat',     Rec, '11', trt.man,     trt.hat);
        add('storeItem',  Rec, '1M', trt.store,   trt.item);
        add('storeLoc',   Rec, '11', trt.store,   trt.loc);
        add('manSeen',    Rec, 'MM', trt.man,     trt.loc);
        add('archItem',   Rec, '1M', rt.arch,     trt.item);
        add('archMan',    Rec, '1M', rt.arch,     trt.man);
        add('archStore',  Rec, '1M', rt.arch,     trt.store);
        
        let lands = Lands({ recTypes: { ...rt, ...trt } });
        
        let clients = Set();
        
        let server = U.Wob();
        server.desc = 'Spoofy Above server for hinterlands tests';
        server.spoofClient = () => {
          let cpuId = (cpuIdCnt++).toString(36).padHead(8, '0');
          
          let client = Hog();
          client.cpuId = cpuId;
          client.hear = U.Wob();
          client.tellWob = U.Wob();
          client.tell = (...args) => client.tellWob.wobble(...args);
          client.nextTell = async (fn=null, force='force') => {
            let hold = null;
            let prm = new Promise(rsv => hold = client.tellWob.hold(v => rsv(v)));
            prm.then(() => hold.shut());
            
            let hut = way.hutForClient(client);
            
            if (force) hut.forceSync(force);   // Ensure something is sent back even if no delta results
            if (fn) await fn(hut);  // Some arbitrary 
            
            let tellVal = await prm;
            
            return tellVal;
          };
          
          lands.pool.addCpuConn(server, client);
          server.wobble(client);
          
          clients.add(client);
          client.shutWob().hold(() => clients.rem(client));
          
          return client;
        };
        
        let way = Way({ makeServer: () => server });
        lands.addWay(way);
        way.hutForClient = client => way.lands.hutsBelow.get(client.cpuId);
        
        await lands.open();
        
        testData = { trt, server, lands, way, clients };
        
      };
      k.sandwich.after = () => {
        let shutGroup = Set();
        
        // If these aren't explicitly shut timeouts may cause
        // the program to persist after all tests are complete
        testData.clients.forEach(client => client.shut(shutGroup));
        testData.lands.shut(shutGroup);
      };
      
      U.Keep(k, 'landsGenUid', () => {
        let lands = Lands({ recTypes: rt });
        return { msg: 'Lands uid len is 8', result: lands.nextUid().length === 8 };
      });
      
      U.Keep(k, 'arch', async () => {
        let { trt, server, lands, way } = testData;
        return { msg: 'Lands has "arch"', result: U.isInspiredBy(lands.arch, Rec) };
      });
      
      U.Keep(k, 'relWobDefineFirst', async () => {
        let { trt, server, lands, way } = testData;
        
        let wobbledItem = null;
        HorzScope(lands.arch.relWob(trt.archItem, 0), (dep, { members: [ _, item ] }) => { wobbledItem = item; });
        
        let item = lands.createRec('item', { value: 'item!' });
        let archItem = lands.createRec('archItem', {}, lands.arch, item);
        
        return [
          [ 'relWob returns item', () => !!wobbledItem ],
          [ 'relWob returns correct item', () => wobbledItem === item ]
        ];
        
      });
      
      U.Keep(k, 'relWobCreateFirst', async () => {
        let { trt, server, lands, way } = testData;
        
        let item = lands.createRec('item', { value: 'item!' })
        let archItem = lands.createRec('archItem', {}, lands.arch, item)
        
        let wobbledItem = null;
        HorzScope(lands.arch.relWob(trt.archItem, 0), (dep, { members: [ _, item ] }) => { wobbledItem = item; });
        
        return [
          [ 'relWob returns item', () => !!wobbledItem ],
          [ 'relWob returns correct item', () => wobbledItem === item ]
        ];
        
      });
      
      U.Keep(k, 'connectionSucceeds', async () => {
        let { trt, server, lands, way } = testData;
        
        let client = server.spoofClient();
        return { result: !!client };
      });
      
      U.Keep(k, 'connectHutDefineFirst', async () => {
        let { trt, server, lands, way } = testData;
        
        let wobbledHut = null;
        HorzScope(lands.arch.relWob(rt.archHut, 0), (dep, { members: [ _, hut ] }) => { wobbledHut = hut; });
        
        let client = server.spoofClient();
        
        return [
          [ 'relWob returns item', () => !!wobbledHut ],
          [ 'relWob returns hut', () => U.isInspiredBy(wobbledHut, Hut) ]
        ];
        
      });
      
      U.Keep(k, 'connectHutCreateFirst', async () => {
        let { trt, server, lands, way } = testData;
        
        let client = server.spoofClient();
        
        let wobbledHut = null;
        HorzScope(lands.arch.relWob(rt.archHut, 0), (dep, { members: [ _, hut ] }) => { wobbledHut = hut; });
        
        return [
          [ 'relWob returns item', () => !!wobbledHut ],
          [ 'relWob returns hut', () => U.isInspiredBy(wobbledHut, Hut) ]
        ];
        
      });
      
      U.Keep(k, 'clientShutsHut', async () => {
        
        let { trt, server, lands, way } = testData;
        
        let client = server.spoofClient();
        
        let wobbledHut = null;
        HorzScope(lands.arch.relWob(rt.archHut, 0), (dep, { members: [ _, hut ] }) => {
          wobbledHut = hut;
        });
        
        client.shut();
        
        return { msg: 'hut is shut', result: () => hut.isShut() };
        
      });
      
      U.Keep(k, 'hutShutsClient', async () => {
        
        let { trt, server, lands, way } = testData;
        
        let client = server.spoofClient();
        
        let wobbledHut = null;
        HorzScope(lands.arch.relWob(rt.archHut, 0), (dep, { members: [ _, hut ] }) => { wobbledHut = hut; });
        
        client.shut();
        
        return { msg: 'hut is shut', result: () => hut.isShut() };
        
      });
      
      U.Keep(k, 'getInit').contain(k => {
        
        U.Keep(k, 'noData', async () => {
          
          let { trt, server, lands, way } = testData;
          
          let client = server.spoofClient();
          
          let result = await client.nextTell(() => {
            client.hear.wobble([ { command: 'getInit' }, client.tell ]);
          }, null);
          
          let initData = parseInitData(result);
          return { result: initData === null };
          
        });
        
        U.Keep(k, 'simpleRec', async () => {
          
          let { trt, server, lands, way } = testData;
          
          HorzScope(lands.arch.relWob(rt.archHut, 0), (dep, { members: [ _, hut ] }) => {
            dep(HorzScope(lands.arch.relWob(trt.archItem, 0), (dep, archItem) => {
              hut.followRec(archItem);
              hut.followRec(archItem.members[1]);
            }));
          });
          
          let item = lands.createRec('item', { value: 'item!' });
          let archItem = lands.createRec('archItem', {}, lands.arch, item);
           
          let client = server.spoofClient();
          let result = await client.nextTell(() => {
            client.hear.wobble([ { command: 'getInit' }, client.tell ]);
          });
          
          let initData = parseInitData(result);
          
          return [
            [ 'data is Object', () => U.isType(initData, Object) ],
            [ 'version is 1', () => initData.version === 1 ],
            [ 'command is update', () => initData.command === 'update' ],
            [ 'content is Object', () => U.isType(initData.content, Object) ],
            [ 'content addRec is Object', () => U.isType(initData.content.addRec, Object) ],
            [ 'adds 2 Recs', () => initData.content.addRec.toArr(v => v).length === 2 ],
            [ 'adds item', () => initData.content.addRec.find((v, k) => k === item.uid) ],
            [ 'adds archItem', () => initData.content.addRec.find((v, k) => k === archItem.uid) ]
          ];
          
        });
        
      });
      
      U.Keep(k, 'follow').contain(k => {
        
        U.Keep(k, 'addRecDefineFirst', async () => {
          
          let { trt, server, lands, way } = testData;
          
          HorzScope(lands.arch.relWob(rt.archHut, 0), (dep, archHut) => {
            
            let [ arch, hut ] = archHut.members;
            
            dep(HorzScope(arch.relWob(trt.archItem, 0), (dep, archItem) => {
              
              let [ arch, item ] = archItem.members;
              
              hut.followRec(archItem);
              hut.followRec(item);
              
            }));
            
          });
          
          let client = server.spoofClient();
          let hut = way.hutForClient(client);
          
          let item = lands.createRec('item', { value: 'item!' })
          let archItem = lands.createRec('archItem', {}, lands.arch, item);
          
          let result = await client.nextTell();
          
          return [
            [ 'result is object', () => U.isType(result, Object) ],
            [ 'result isn\'t forced', () => !result.has('force') ],
            [ 'is version 1', () => result.version === 1 ],
            [ 'is update command', () => result.command === 'update' ],
            [ 'result content is Object', () => U.isType(result.content, Object) ],
            [ 'content addRec is Object', () => U.isType(result.content.addRec, Object) ],
            [ 'add 2 Recs', () => result.content.addRec.toArr(v => v).length === 2 ],
            [ 'add includes item', () => result.content.addRec.find((v, k) => v.type === item.type.name && k === item.uid && v.value === 'item!') ],
            [ 'add includes archItem', () => result.content.addRec.find((v, k) => v.type === archItem.type.name && k === archItem.uid) ],
          ];
          
        });
        
        U.Keep(k, 'addRecCreateFirst', async () => {
          
          let { trt, server, lands, way } = testData;
          
          let client = server.spoofClient();
          let hut = way.hutForClient(client);
          
          let item = lands.createRec('item', { value: 'item!' });
          let archItem = lands.createRec('archItem', {}, lands.arch, item);
          
          HorzScope(lands.arch.relWob(rt.archHut, 0), (dep, archHut) => {
            
            let [ arch, hut ] = archHut.members;
            
            dep(HorzScope(arch.relWob(trt.archItem, 0), (dep, archItem) => {
              
              let [ arch, item ] = archItem.members;
              
              hut.followRec(archItem);
              hut.followRec(item);
              
            }));
            
          });
          
          let result = await client.nextTell();
          
          return [
            [ 'result is object', () => U.isType(result, Object) ],
            [ 'result isn\'t forced', () => !result.has('force') ],
            [ 'is version 1', () => result.version === 1 ],
            [ 'is update command', () => result.command === 'update' ],
            [ 'result content is Object', () => U.isType(result.content, Object) ],
            [ 'content addRec is Object', () => U.isType(result.content.addRec, Object) ],
            [ 'add 2 Recs', () => result.content.addRec.toArr(v => v).length === 2 ],
            [ 'add includes item', () => result.content.addRec.find((v, k) => v.type === item.type.name && k === item.uid && v.value === 'item!') ],
            [ 'add includes archItem', () => result.content.addRec.find((v, k) => v.type === archItem.type.name && k === archItem.uid) ],
          ];
          
        });
        
        U.Keep(k, 'updRec1', async () => {
          
          let { trt, server, lands, way } = testData;
          
          HorzScope(lands.arch.relWob(rt.archHut, 0), (dep, archHut) => {
            let [ arch, hut ] = archHut.members;
            dep(HorzScope(arch.relWob(trt.archItem, 0), (dep, archItem) => {
              let [ arch, item ] = archItem.members;
              hut.followRec(archItem);
              hut.followRec(item);
            }));
          });
          
          let client = server.spoofClient();
          let hut = way.hutForClient(client);
          
          let item = lands.createRec('item', { value: 'item!' });
          let archItem = lands.createRec('archItem', {}, lands.arch, item);
          
          // Get addRec
          let result = await client.nextTell();
          
          // Get updRec
          result = await client.nextTell(() => item.wobble('Wheee'));
          
          return [
            [ 'result is object', () => U.isType(result, Object) ],
            [ 'result isn\'t forced', () => !result.has('force') ],
            [ 'is version 2', () => result.version === 2 ],
            [ 'is update command', () => result.command === 'update' ],
            [ 'result content is Object', () => U.isType(result.content, Object) ],
            [ 'content updRec is Object', () => U.isType(result.content.updRec, Object) ],
            [ 'upd 1 Rec', () => result.content.updRec.toArr(v => v).length === 1 ],
            [ 'upd item to correct value', () => result.content.updRec.find((v, k) => k === item.uid && v === 'Wheee') ],
          ];
          
        });
        
        U.Keep(k, 'remRec1', async () => {
          
          let { trt, server, lands, way } = testData;
          
          HorzScope(lands.arch.relWob(rt.archHut, 0), (dep, archHut) => {
            
            let [ arch, hut ] = archHut.members;
            
            dep(HorzScope(arch.relWob(trt.archItem, 0), (dep, archItem) => {
              
              let [ arch, item ] = archItem.members;
              
              hut.followRec(archItem);
              hut.followRec(item);
              
            }));
            
          });
          
          let client = server.spoofClient();
          let hut = way.hutForClient(client);
          
          let item = lands.createRec('item', { value: 'item!' });
          let archItem = lands.createRec('archItem', {}, lands.arch, item);
          
          let result = await client.nextTell();
          
          result = await client.nextTell(() => {
            archItem.shut();
          });
          
          return [
            [ 'result is object', () => U.isType(result, Object) ],
            [ 'result isn\'t forced', () => !result.has('force') ],
            [ 'is version 2', () => result.version === 2 ],
            [ 'is update command', () => result.command === 'update' ],
            [ 'result content is Object', () => U.isType(result.content, Object) ],
            [ 'content remRec is Object', () => U.isType(result.content.remRec, Object) ],
            [ 'rem 1 Rec', () => result.content.remRec.toArr(v => v).length === 1 ],
            [ 'rem archItem', () => result.content.remRec.find((v, k) => k === archItem.uid) ]
          ];
          
        });
        
        U.Keep(k, 'remRec2', async () => {
          
          let { trt, server, lands, way } = testData;
          
          HorzScope(lands.arch.relWob(rt.archHut, 0), (dep, archHut) => {
            
            let [ arch, hut ] = archHut.members;
            
            dep(HorzScope(arch.relWob(trt.archItem, 0), (dep, archItem) => {
              
              let [ arch, item ] = archItem.members;
              
              hut.followRec(archItem);
              hut.followRec(item);
              
            }));
            
          });
          
          let client = server.spoofClient();
          let hut = way.hutForClient(client);
          
          let item = lands.createRec('item', { value: 'item!' });
          let archItem = lands.createRec('archItem', {}, lands.arch, item);
          
          // Get addRec
          let result = await client.nextTell();
          
          // Get remRec
          result = await client.nextTell(() => item.shut());
          
          // TODO: Really, we only need to send "remRec" for `item`, as its
          // removal will automatically remove `archItem` from below as well.
          // This isn't taken into consideration at the moment. Instead all
          // Recs whose shutting occurs as a result of a single operation are
          // individually synced shut on the Below's end.
          
          return [
            [ 'result is object', () => U.isType(result, Object) ],
            [ 'result isn\'t forced', () => !result.has('force') ],
            [ 'is version 2', () => result.version === 2 ],
            [ 'is update command', () => result.command === 'update' ],
            [ 'result content is Object', () => U.isType(result.content, Object) ],
            [ 'content remRec is Object', () => U.isType(result.content.remRec, Object) ],
            [ 'rem 2 Recs', () => result.content.remRec.toArr(v => v).length === 2 ],
            [ 'rem item', () => result.content.remRec.find((v, k) => k === item.uid) ],
            [ 'rem archItem', () => result.content.remRec.find((v, k) => k === archItem.uid) ]
          ];
          
        });
        
        U.Keep(k, 'multi').contain(k => {
          
          U.Keep(k, 'addSyncRemSyncAddSync', async () => {
            
            let { trt, server, lands, way } = testData;
            
            HorzScope(lands.arch.relWob(rt.archHut, 0), (dep, archHut) => {
              let [ arch, hut ] = archHut.members;
              dep(HorzScope(arch.relWob(trt.archItem, 0), (dep, archItem) => {
                let [ arch, item ] = archItem.members;
                hut.followRec(item);
                hut.followRec(archItem);
              }));
            });
            
            let item = lands.createRec('item', { value: 'item!' });
            let archItem = lands.createRec('archItem', {}, lands.arch, item);
            
            let client = server.spoofClient();
            let hut = way.hutForClient(client);
            
            // Get addRec for `item` and `archItem`
            let result1 = await client.nextTell();
            
            // Unfollow `archItem`
            let str = hut.getRecFollowStrength(archItem);
            let result2 = await client.nextTell(() => {
              hut.setRecFollowStrength(archItem, 0);
            });
            
            // Follow `archItem` again
            let result3 = await client.nextTell(() => {
              hut.setRecFollowStrength(archItem, str);
            });
            
            return [
              [ 'result is object', () => U.isType(result3, Object) ],
              [ 'is version 3', () => result3.version === 3 ],
              [ 'is update command', () => result3.command === 'update' ],
              [ 'result content is Object', () => U.isType(result3.content, Object) ],
              [ 'content addRec is Object', () => U.isType(result3.content.addRec, Object) ],
              [ 'adds 1 Rec', () => result3.content.addRec.toArr(v => v).length === 1 ],
              [ 'content addRec is correct', () => result3.content.addRec.find((v, k) => k === archItem.uid) ],
            ];
            
          });
          
          U.Keep(k, 'addSyncRemAddSync', async () => {
            
            let { trt, server, lands, way } = testData;
            
            HorzScope(lands.arch.relWob(rt.archHut, 0), (dep, archHut) => {
              let [ arch, hut ] = archHut.members;
              dep(HorzScope(arch.relWob(trt.archItem, 0), (dep, archItem) => {
                let [ arch, item ] = archItem.members;
                hut.followRec(item);
                hut.followRec(archItem);
              }));
            });
            
            let item = lands.createRec('item', { value: 'item!' });
            let archItem = lands.createRec('archItem', {}, lands.arch, item);
            
            let client = server.spoofClient();
            let hut = way.hutForClient(client);
            
            // Get addRec for `item` and `archItem`
            let result1 = await client.nextTell();
            
            // Unfollow and follow `archItem`
            let result2 = await client.nextTell(() => {
              let str = hut.getRecFollowStrength(archItem);
              hut.setRecFollowStrength(archItem, 0);
              hut.setRecFollowStrength(archItem, str);
            });
            
            return [
              [ 'result is object', () => U.isType(result2, Object) ],
              [ 'is version 2', () => result2.version === 2 ],
              [ 'is update command', () => result2.command === 'update' ],
              [ 'result content is Object', () => U.isType(result2.content, Object) ],
              [ 'content has no addRec', () => !result2.content.has('addRec') ],
              [ 'content has no remRec', () => !result2.content.has('remRec') ],
            ];
            
          });
          
          U.Keep(k, 'addRemSync1', async () => {
            
            let { trt, server, lands, way } = testData;
            
            HorzScope(lands.arch.relWob(rt.archHut, 0), (dep, archHut) => {
              let [ arch, hut ] = archHut.members;
              dep(HorzScope(arch.relWob(trt.archItem, 0), (dep, archItem) => {
                let [ arch, item ] = archItem.members;
                hut.followRec(item);
                hut.followRec(archItem);
              }));
            });
            
            let client = server.spoofClient();
            let hut = way.hutForClient(client);
            
            let item = lands.createRec('item', { value: 'item!' });
            let archItem = lands.createRec('archItem', {}, lands.arch, item);
            hut.setRecFollowStrength(archItem, 0);
            
            // Get addRec for `item` and `archItem`
            let result = await client.nextTell();
            
            return [
              [ 'result is Object', () => U.isType(result, Object) ],
              [ 'is version 1', () => result.version === 1 ],
              [ 'is update command', () => result.command === 'update' ],
              [ 'result content is Object', () => U.isType(result.content, Object) ],
              [ 'content addRec is Object', () => U.isType(result.content.addRec, Object) ],
              [ 'adds 1 Rec', () => result.content.addRec.toArr(v => v).length === 1 ],
              [ 'adds correct Rec', () => result.content.addRec.find((v, k) => k === item.uid) ],
            ];
            
          });
          
          U.Keep(k, 'addRemSync2', async () => {
            
            let { trt, server, lands, way } = testData;
            
            HorzScope(lands.arch.relWob(rt.archHut, 0), (dep, archHut) => {
              let [ arch, hut ] = archHut.members;
              dep(HorzScope(arch.relWob(trt.archItem, 0), (dep, archItem) => {
                let [ arch, item ] = archItem.members;
                hut.followRec(item);
                hut.followRec(archItem);
              }));
            });
            
            let client = server.spoofClient();
            let hut = way.hutForClient(client);
            
            let item = lands.createRec('item', { value: 'item!' });
            let archItem = lands.createRec('archItem', {}, lands.arch, item);
            archItem.shut();
            
            // Get addRec for `item` and `archItem`
            let result = await client.nextTell();
            
            return [
              [ 'result is Object', () => U.isType(result, Object) ],
              [ 'is version 1', () => result.version === 1 ],
              [ 'is update command', () => result.command === 'update' ],
              [ 'result content is Object', () => U.isType(result.content, Object) ],
              [ 'content addRec is Object', () => U.isType(result.content.addRec, Object) ],
              [ 'adds 1 Rec', () => result.content.addRec.toArr(v => v).length === 1 ],
              [ 'adds correct Rec', () => result.content.addRec.find((v, k) => k === item.uid) ],
            ];
            
          });
          
        });
        
      });
      
      U.Keep(k, 'aboveAndBelow').contain(k => {
        
        let mock2PartyData = null;
        k.sandwich.before = async () => {
          
          // `serverAbove` wobbles clients representing Belows
          // `serverBelow` wobbles a single client representing its Above
          
          let { trt, server: serverAbove, lands, way } = testData;
          
          let addClientBelow = (name, fn=null) => {
            
            let recTypes = { ...rt, ...trt };
            
            // Combine hinterlands RecTypes (`rt`) along with RecTypes for tests (`trt`)
            let state = { version: 0, recTypes, allRecs: Map(), server: null, holds: [] };
            state.createRec = (type, ...args) => recTypes[type].create(...args);
            state.arch = rt.arch.create({ uid: '!arch' });
            
            let cpuIdCnt = 0;
            let serverBelow = state.server = U.Wob();
            serverBelow.desc = 'Spoofy Below server for hinterlands tests';
            serverBelow.spoofClient = () => {
              let cpuId = (cpuIdCnt++).toString(36).padHead(8, '0');
              
              let aboveClient = Hog();
              aboveClient.cpuId = cpuId;
              aboveClient.hear = U.Wob();
              aboveClient.tellWob = U.Wob();
              aboveClient.tell = (...args) => aboveClient.tellWob.wobble(...args);
              aboveClient.nextHear = async (fn=null, force='force') => {
                
                let timeout = null;
                let hold = null;
                let prm = new Promise(rsv => {
                  hold = aboveClient.hear.hold((...args) => { 'Resolves "nextHear" promise'; rsv(...args); });
                  timeout = setTimeout(() => rsv([ { force }, () => { throw new Error('No reply available!'); } ]), 20);
                });
                
                if (fn) fn();
                
                let [ msg, reply ] = await prm; // We ignore "reply" here
                clearTimeout(timeout);
                hold.shut();
                
                return msg;
                
              };
              
              lands.pool.addCpuConn(serverBelow, aboveClient);
              serverBelow.wobble(aboveClient);
              
              return aboveClient;
            };
            
            if (fn) fn(state, serverBelow);
            
            state.fresh = () => {
              
              state.version = 0;
              state.lands = lands;
              state.arch = rt.arch.create({ uid: '!arch' });
              state.allRecs = Map([ [ state.arch.uid, state.arch ] ]);
              state.holds.forEach(hold => !hold.isShut() && hold.shut()); // Close any open holds
              
              // `aboveClient` is `serverAbove`'s representation of Below
              let aboveClient = serverAbove.spoofClient();
              
              // `belowClient` is `serverBelow`'s only Client, and representation of Above
              // Generated by the function just above!
              let belowClient = serverBelow.spoofClient();
              
              state.tell = (msg) => {
                belowClient.tell([ msg, (...args) => aboveClient.tell(...args) ]);
              };
              
              // Here's how messages from Above hit Below! Note that a "reply" function
              // is included
              state.holds.push(aboveClient.tellWob.hold(msg => {
                belowClient.hear.wobble([ msg, () => { throw new Error('No reply available'); } ])
              }));
              
              // Here's how messages from Below hit Above. Note that any "reply" function
              // will already be included in `args`
              state.holds.push(belowClient.tellWob.hold((...args) => aboveClient.hear.wobble(...args)));
              
              return [ aboveClient, belowClient ];
              
            };
            
            return state;
            
          };
          
          mock2PartyData = { addClientBelow, above: testData };
          
        };
        k.sandwich.after = () => {
        };
        
        U.Keep(k, 'connectedness', async () => {
          
          let { trt, server: serverAbove, lands, way } = mock2PartyData.above;
          let below1 = mock2PartyData.addClientBelow('testBelow1');
          let [ aboveClient, belowClient ] = below1.fresh();
          
          let heard = await belowClient.nextHear(() => below1.tell({ command: 'getInit' }));
          
          return { msg: 'heard something', result: !U.isType(heard, Object) || !heard.has('force') };
          
        });
        
        U.Keep(k, 'getInitHtml', async () => {
          
          let { trt, server: serverAbove, lands, way } = mock2PartyData.above;
          let below1 = mock2PartyData.addClientBelow('testBelow1');
          let [ aboveClient, belowClient ] = below1.fresh();
          
          let heardData = await belowClient.nextHear(() => below1.tell({ command: 'getInit' }));
          
          return [
            [ 'response is String', () => U.isType(heardData, String) ],
            [ 'response looks like html', () => heardData.hasHead('<!DOCTYPE html>') ]
          ];
          
        });
        
        U.Keep(k, 'mockBelow').contain(k => {
          
          let gatherAllRecs = (rec, allRecs={}) => {
            
            if (allRecs.has(rec.uid)) return allRecs;
            allRecs[rec.uid] = rec;
            
            // Include all MemberRecs
            rec.members.forEach(mem => gatherAllRecs(mem, allRecs));
            
            // Include all GroupRecs
            rec.relWobs.forEach(relWob => relWob.toArr(v => v).forEach(rec0 => gatherAllRecs(rec0, allRecs)));
            
            return allRecs;
            
          };
          let aboveBelowDiff = (lands, state) => {
            
            let [ aboveRecs, belowRecs ] = [ lands.arch, state.arch ].map(r => gatherAllRecs(r));
            
            let onlyInAbove = aboveRecs.map((rec, uid) => belowRecs.has(uid) ? C.skip : rec);
            let onlyInBelow = belowRecs.map((rec, uid) => aboveRecs.has(uid) ? C.skip : rec);
            let valueMismatch = aboveRecs.toArr((rec, uid) =>
              (belowRecs.has(uid) && belowRecs[uid].value !== rec.value)
                ? { above: rec, below: belowRecs[uid] }
                : C.skip
            );
            let match = onlyInAbove.isEmpty() && onlyInBelow.isEmpty() && valueMismatch.isEmpty();
            
            return { onlyInAbove, onlyInBelow, valueMismatch, match };
            
          };
          k.sandwich.before = () => {
            
            mock2PartyData.addMockedClientBelow = name => {
              
              return mock2PartyData.addClientBelow(name, state => {
                state.server.hold(client => client.hear.hold(([ msg, reply ]) => {
                  
                  // This happens whenever the Below hears anything
                  
                  if (U.isType(msg, String)) {
                    
                    if (msg.hasHead('<!DOCTYPE html>')) {
                      
                      let initData = parseInitData(msg);
                      if (initData) doUpdate(state, initData);
                      
                    }
                    
                  } else if (U.isType(msg, Object)) {
                    
                    if (msg.has('command')) {
                      
                      if (msg.command === 'update') {
                        
                        doUpdate(state, msg);
                        
                      } else {
                        
                        throw new Error(`Command not supported: "${msg.command}"`);
                        
                      }
                      
                    }
                    
                  }
                  
                }));
              });
              
            };
            
          };
          k.sandwich.after = () => {};
          
          U.Keep(k, 'getInitHtml', async () => {
            
            let { trt, server: serverAbove, lands, way } = mock2PartyData.above;
            let below1 = mock2PartyData.addMockedClientBelow('testBelow1');
            let [ aboveClient, belowClient ] = below1.fresh();
            
            let heardData = await belowClient.nextHear(() => below1.tell({ command: 'getInit' }));
            
            return [
              [ 'response is String', () => U.isType(heardData, String) ],
              [ 'response looks like html', () => heardData.hasHead('<!DOCTYPE html>') ]
            ];
            
          });
          
          U.Keep(k, 'getInitAndSyncRaw', async () => {
            
            let { trt, server: serverAbove, lands, way } = mock2PartyData.above;
            let below1 = mock2PartyData.addMockedClientBelow('testBelow1');
            let [ aboveClient, belowClient ] = below1.fresh();
            
            HorzScope(lands.arch.relWob(rt.archHut, 0), (dep, archHut) => {
              
              let [ arch, hut ] = archHut.members;
              dep(HorzScope(arch.relWob(trt.archItem, 0), (dep, archItem) => {
                
                let [ _, item ] = archItem.members;
                hut.followRec(archItem);
                hut.followRec(item);
                
              }));
              
            });
            
            let heardData1 = await belowClient.nextHear(() => below1.tell({ command: 'getInit' }));
            
            let item = lands.createRec('item', { value: 'item!' });
            let archItem = lands.createRec('archItem', {}, lands.arch, item);
            
            let heardData2 = await belowClient.nextHear();
            
            return [
              [ 'got Object', () => U.isType(heardData2, Object) ],
              [ 'object version 1', () => heardData2.version === 1 ],
              [ 'command is "update"', () => heardData2.command === 'update' ],
              [ 'command content is Object', () => U.isType(heardData2.content, Object) ],
              [ 'content addRec is Object', () => U.isType(heardData2.content.addRec, Object) ],
              [ 'adds 2 Recs', () => heardData2.content.addRec.toArr(v => v).length === 2 ],
              [ 'adds item', () => heardData2.content.addRec.find((v, uid) => uid === item.uid) ],
              [ 'adds archItem', () => heardData2.content.addRec.find((v, uid) => uid === archItem.uid) ]
            ];
            
          });
          
          U.Keep(k, 'getInitAndSync', async () => {
            
            let { trt, server: serverAbove, lands, way } = mock2PartyData.above;
            let below1 = mock2PartyData.addMockedClientBelow('testBelow1');
            let [ aboveClient, belowClient ] = below1.fresh();
            
            HorzScope(lands.arch.relWob(rt.archHut, 0), (dep, archHut) => {
              let [ arch, hut ] = archHut.members;
              dep(HorzScope(arch.relWob(trt.archItem, 0), (dep, archItem) => {
                let [ _, item ] = archItem.members;
                hut.followRec(archItem);
                hut.followRec(item);
              }));
            });
            
            await belowClient.nextHear(() => below1.tell({ command: 'getInit' }));
            
            let item = lands.createRec('item', { value: 'item!' });
            let archItem = lands.createRec('archItem', {}, lands.arch, item);
            
            await belowClient.nextHear();
            
            return [
              [ 'synced archItem', () => below1.arch.relWob(trt.archItem, 0).toArr(v => v).length === 1 ],
              [ 'synced item', () => {
                let archItemBelow = below1.arch.relWob(trt.archItem, 0).toArr(v => v)[0];
                let itemBelow = archItemBelow.members.find(rec => rec.type === trt.item);
                if (!itemBelow) return false;
                else            itemBelow = itemBelow[0];
                return itemBelow && itemBelow.uid === item.uid && itemBelow !== item;
                //below1.arch.relWob(trt.archItem, 0).toArr(v => v).find(v => 1).members.find(v => v.type.name === 'item') ]
              }]
            ];
            
          });
          
          U.Keep(k, 'multipleGetInit', async () => {
            
            let { trt, server: serverAbove, lands, way } = mock2PartyData.above;
            let below1 = mock2PartyData.addMockedClientBelow('testBelow1');
            
            HorzScope(lands.arch.relWob(rt.archHut, 0), (dep, archHut) => {
              let [ arch, hut ] = archHut.members;
              dep(HorzScope(arch.relWob(trt.archItem, 0), (dep, archItem) => {
                let [ _, item ] = archItem.members;
                hut.followRec(archItem);
                hut.followRec(item);
              }));
            });
            
            // Reset a bunch of times
            let [ aboveClient, belowClient ] = [ null, null ];
            for (let i = 0; i < 10; i++) {
              [ aboveClient, belowClient ] = below1.fresh();
              below1.tell({ command: 'getInit' })
              await belowClient.nextHear();
            }
            
            let item = lands.createRec('item', { value: 'item!' });
            let archItem = lands.createRec('archItem', {}, lands.arch, item);
            
            await belowClient.nextHear();
            
            return [
              [ 'synced archItem', () => below1.arch.relWob(trt.archItem, 0).toArr(v => v).length === 1 ],
              [ 'synced item', () => {
                let archItemBelow = below1.arch.relWob(trt.archItem, 0).toArr(v => v)[0];
                let itemBelow = archItemBelow.members.find(rec => rec.type === trt.item);
                return itemBelow && itemBelow[0].uid === item.uid && itemBelow[0] !== item;
              }]
            ];
            
          });
          
          U.Keep(k, 'updSync', async () => {
            
            let { trt, server: serverAbove, lands, way } = mock2PartyData.above;
            let below1 = mock2PartyData.addMockedClientBelow('testBelow1');
            
            HorzScope(lands.arch.relWob(rt.archHut, 0), (dep, archHut) => {
              let [ arch, hut ] = archHut.members;
              dep(HorzScope(arch.relWob(trt.archItem, 0), (dep, archItem) => {
                let [ _, item ] = archItem.members;
                hut.followRec(item);
                hut.followRec(archItem);
              }));
            });
            
            let [ aboveClient, belowClient ] = below1.fresh();
            
            await belowClient.nextHear(() => below1.tell({ command: 'getInit' }));
            
            let item = lands.createRec('item', { value: 'item1' });
            let archItem = lands.createRec('archItem', {}, lands.arch, item);
            
            await belowClient.nextHear();
            
            item.modify(v => `${v}-modified`);
            
            await belowClient.nextHear();
            
            let diff = aboveBelowDiff(lands, below1);
            return [
              [ 'diff not empty', () => !diff.match ],
              [ 'above is superset of below', () => diff.onlyInBelow.isEmpty() ],
              [ 'above has 2 extra Recs', () => diff.onlyInAbove.toArr(v => v).length === 2 ],
              [ 'only above has hut', () => diff.onlyInAbove.find(rec => rec.type.name === 'hut') ],
              [ 'only above has archHut', () => diff.onlyInAbove.find(rec => rec.type.name === 'archHut') ]
            ];
            
          });
          
          U.Keep(k, 'remSyncRaw', async () => {
            
            let { trt, server: serverAbove, lands, way } = mock2PartyData.above;
            let below1 = mock2PartyData.addMockedClientBelow('testBelow1');
            
            HorzScope(lands.arch.relWob(rt.archHut, 0), (dep, archHut) => {
              let [ arch, hut ] = archHut.members;
              dep(HorzScope(arch.relWob(trt.archItem, 0), (dep, archItem) => {
                let [ _, item ] = archItem.members;
                hut.followRec(item);
                hut.followRec(archItem);
              }));
            });
            
            let [ aboveClient, belowClient ] = below1.fresh();
            let item, archItem;
            
            let v0 = await belowClient.nextHear();
            
            let v1 = await belowClient.nextHear(() => {
              item = lands.createRec('item', { value: 'item1' });
              archItem = lands.createRec('archItem', {}, lands.arch, item);
            });
            
            let sync = await belowClient.nextHear(() => item.shut());
            
            return [
              [ 'sync is Object', () => U.isType(sync, Object) ],
              [ 'sync is version 2', () => sync.version === 2 ],
              [ 'sync command is "update"', () => sync.command === 'update' ],
              [ 'sync content is Object', () => U.isType(sync.content, Object) ],
              [ 'sync does remRec', () => U.isType(sync.content.remRec, Object) ],
              [ 'sync rems 2 Recs', () => sync.content.remRec.toArr(v => v).length === 2 ],
              [ 'sync rems item', () => sync.content.remRec.find((r, uid) => uid === item.uid) ],
              [ 'sync rems archItem', () => sync.content.remRec.find((r, uid) => uid === archItem.uid) ]
            ];
            
          });
          
          U.Keep(k, 'remSync', async () => {
            
            let { trt, server: serverAbove, lands, way } = mock2PartyData.above;
            let below1 = mock2PartyData.addMockedClientBelow('testBelow1');
            
            HorzScope(lands.arch.relWob(rt.archHut, 0), (dep, archHut) => {
              let [ arch, hut ] = archHut.members;
              dep(HorzScope(arch.relWob(trt.archItem, 0), (dep, archItem) => {
                let [ _, item ] = archItem.members;
                hut.followRec(item);
                hut.followRec(archItem);
              }));
            });
            
            let [ aboveClient, belowClient ] = below1.fresh();
            
            await belowClient.nextHear(() => below1.tell({ command: 'getInit' }));
            
            let item = lands.createRec('item', { value: 'item1' });
            let archItem = lands.createRec('archItem', {}, lands.arch, item);
            
            await belowClient.nextHear();
            
            item.shut();
            
            let remResult = await belowClient.nextHear();
            
            let diff = aboveBelowDiff(lands, below1);
            
            return [
              [ 'archItem removed', () => below1.arch.relWob(trt.archItem, 0).size() === 0 ],
              [ 'above is superset of below', () => diff.onlyInBelow.isEmpty() ],
              [ 'above has 2 extra Recs', () => diff.onlyInAbove.toArr(v => v).length === 2 ],
              [ 'only above has hut', () => diff.onlyInAbove.find(rec => rec.type.name === 'hut') ],
              [ 'only above has archHut', () => diff.onlyInAbove.find(rec => rec.type.name === 'archHut') ],
              [ 'no value mismatches', () => diff.valueMismatch.isEmpty() ]
            ];
            
          });
          
        });
        
      });
      
    });
    
    /// =TEST}
    
    return content;
  }
});
